tabcosting <- tabPanel("Costing", value = "costing_tab", 
         fluidRow(
             column(3,
                    h2("Unit cost"),
                    wellPanel(class = "mypanel", 
                              numericInput("perkm",
                                           "Travel per km $",
                                           value = 0,
                                           min = 0,
                                           max = 1000,
                                           step = 0.1,
                                           width = 200),
                              numericInput("perarray",
                                           "Cost per array $",
                                           min = 0,
                                           max = 10000,
                                           value = 0,
                                           step=0.1,
                                           width = 200),
                              numericInput("perdetector",
                                           "Cost per detector $",
                                           min = 0,
                                           max = 1000,
                                           value = 0,
                                           step=0.1,
                                           width = 200),
                              numericInput("pervisit",
                                           "Cost per detector visit $",
                                           min = 0,
                                           max = 1000,
                                           value = 0,
                                           step=0.1,
                                           width = 200),
                              numericInput("perdetection",
                                           "Cost per detection $",
                                           min = 0,
                                           max = 1000,
                                           value = 0,
                                           step=0.1,
                                           width = 200)),
                    br(),
                    fluidRow(
                        column(10, offset=1, checkboxInput("setupoccasion", "Include setup occasion", TRUE))
                    )
             ),
             column(3, offset = 0,
                    h2("Route"),
                    wellPanel(class = "mypanel", 
                              radioButtons("routetype", label = "Type",
                                           choices = c("Sequential", "Manual", "SumSpacing")),
                              #   choices = c("Sequential", "SumSpacing", "TSP", "Manual")),
                              # selectInput("TSPmethod",
                              #             "TSP method",
                              #             c("two_opt", "farthest_insertion", "nearest_insertion", "nn"),
                              #             "farthest_insertion",
                              #             width = 200),
                              # numericInput("TSPrepl",
                              #              "TSP replicates",
                              #              min = 1, max = 10000,
                              #              value = 100,
                              #              step=1,
                              #              width=180),
                              checkboxInput("returnbox", "Return to start",
                                            value = FALSE,
                                            width = 180)
                    ),
                    br(),
                    plotOutput("routePlot", click = "click", height=320),
                    conditionalPanel("input.routetype == 'Manual'",
                                     actionButton("routebtn", "Define new route by clicking at vertices",
                                                  width = 270))
                    
             ),
             column(4,
                    h2("Current costing"),
                    verbatimTextOutput("costPrint")
             )
         )
)